route:
  group_by: ['alertname']
  group_interval: 120s
  repeat_interval: 7200s
  group_wait: 180s
  receiver: 'IoT-backend'

  routes:
  - receiver: 'IoT-backend'
    match_re:
      #job: example
      severity: 'warning'
      #group: example
    continue: true 

receivers:
  - name: 'IoT-backend'
    webhook_configs:
      - send_resolved: True
        url: http://telegram_bot:9087/alert/-301486420
