{
 "title": "HTTP Requests",
 "description": "Example Dashboard from http app",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP requests rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval]) * 60",
     "legendFormat": "HTTP response: {{code}}"
    }
   ]
  },
  {
   "title": "HTTP request overview",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "HTTP response: {{code}}" }
   ]
  },
  {
   "title": "Response Duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le))\n"
    }
   ]
  }
 ]
}