global:
  scrape_interval:     20s
  evaluation_interval: 20s
  external_labels:
    monitor: 'prometheus-IoT'

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval:     10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'example-app'
    scrape_interval:     10s
    static_configs:
      - targets: ['example-app:8080']

  - job_name: 'pushgateway'
    scrape_interval:     10s
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node-exporter'
    scrape_interval:     10s
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'blackbox'
    # scheme: http
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    scrape_interval:     60s
    static_configs:
      - targets:
        - https://inuits.cz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

